services:
  ai-proxy:
    build: .
    container_name: ai_proxy_test
    ports:
      - "7000:8000"
    networks:
      - ai_gateway_ai_network
    restart: always

networks:
  ai_gateway_ai_network:
    external: true
